[theme]
primaryColor = "#38bdf8"
backgroundColor = "#020617"
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
address = "0.0.0.0"
port = 5000
